name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test basic imports
      run: |
        python -c "import gradio; print('✅ Gradio imported successfully')"
        python -c "import openai; print('✅ OpenAI imported successfully')"
        python -c "import pypdf; print('✅ PyPDF imported successfully')"
        python -c "import requests; print('✅ Requests imported successfully')"
        python -c "import dotenv; print('✅ Python-dotenv imported successfully')"

    - name: Test app structure
      run: |
        python -c "
        import app
        print('✅ App module imported successfully')
        print('✅ Available functions:', [f for f in dir(app) if not f.startswith('_')])
        "

    - name: Check file structure
      run: |
        echo "📁 Checking project structure..."
        ls -la
        echo "📄 Checking me/ directory..."
        ls -la me/
        echo "✅ File structure looks good"

    - name: Build status
      run: |
        echo "✅ Build completed successfully!"
        echo "Project is ready for deployment"
