name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test import
      run: |
        python -c "import app; print('App imports successfully')"

    - name: Check Gradio app
      run: |
        python -c "
        import gradio as gr
        from app import Me
        me = Me()
        print('Gradio app and Me class initialized successfully')
        "

    - name: Build status
      run: |
        echo "✅ Build completed successfully!"
        echo "Project is ready for deployment"
